const {SlashCommandBuilder,PermissionFlagsBits}=require("discord.js");
const {db}=require("../firebase");
const {getGuildConfig}=require("../lib/guildConfig");
const {COLORS,EMOJIS,card}=require("../lib/ui");
const sessions=new Map(),voiceSessions=new Map(),totals=new Map();
const ref=(g,u)=>db.collection("guilds").doc(g).collection("activeTime").doc(u);
const format=ms=>{const m=Math.floor(ms/60000);return Math.floor(m/60)+"h "+m%60+"m";};
const isStaff=(m,c)=>!!m&&!m.user.bot&&(!c.activeTime.staffRoleId||m.roles.cache.has(c.activeTime.staffRoleId)||m.permissions.has(PermissionFlagsBits.Administrator));
const add=(map,id,key,ms)=>{const d=map.get(id)||{};d[key]=(d[key]||0)+ms;map.set(id,d);};
async function load(g){const map=new Map();const s=await db.collection("guilds").doc(g.id).collection("activeTime").get();s.forEach(d=>map.set(d.id,d.data()||{}));totals.set(g.id,map);const c=await getGuildConfig(g.id);for(const m of g.members.cache.values()){if(!isStaff(m,c))continue;const k=g.id+":"+m.id;if(m.presence?.status&&m.presence.status!=="offline")sessions.set(k,Date.now());if(m.voice?.channelId)voiceSessions.set(k,Date.now());}}
async function save(gid){const map=totals.get(gid);if(!map)return;const b=db.batch();for(const [id,d] of map)b.set(ref(gid,id),{activeTime:d.activeTime||0,voiceTime:d.voiceTime||0,messages:d.messages||0,commands:d.commands||0,updatedAt:new Date()},{merge:true});await b.commit();}
async function snapshot(gid){const now=Date.now(),map=totals.get(gid)||new Map();for(const [k,t] of sessions)if(k.startsWith(gid+":")){add(map,k.slice(gid.length+1),"activeTime",now-t);sessions.set(k,now);}for(const [k,t] of voiceSessions)if(k.startsWith(gid+":")){add(map,k.slice(gid.length+1),"voiceTime",now-t);voiceSessions.set(k,now);}await save(gid);}
async function report(g){const c=await getGuildConfig(g.id);if(!c.activeTime.logChannelId)return false;await snapshot(g.id);const rows=[...(totals.get(g.id)||new Map())].filter(x=>(x[1].activeTime||0)+(x[1].voiceTime||0)+(x[1].messages||0)+(x[1].commands||0)>0).sort((a,b)=>(b[1].activeTime||0)-(a[1].activeTime||0));const body=rows.length?rows.map(x=>"<@"+x[0]+"> • 🟢 **"+format(x[1].activeTime||0)+"** • 🎙️ **"+format(x[1].voiceTime||0)+"** • 💬 **"+(x[1].messages||0)+"** • ⚙️ **"+(x[1].commands||0)+"**").join("\n"):"No staff activity recorded today.";const ch=await g.client.channels.fetch(c.activeTime.logChannelId).catch(()=>null);if(!ch)return false;await ch.send(card(c,EMOJIS.STATS+" Daily Staff Activity",body,"Active Time",COLORS.SKY_BLUE));return true;}
async function reset(g){await snapshot(g.id);const map=totals.get(g.id)||new Map(),b=db.batch(),now=Date.now();for(const id of map.keys())b.set(ref(g.id,id),{activeTime:0,voiceTime:0,messages:0,commands:0,updatedAt:new Date()},{merge:true});await b.commit();for(const d of map.values()){d.activeTime=0;d.voiceTime=0;d.messages=0;d.commands=0;}for(const [k] of sessions)if(k.startsWith(g.id+":"))sessions.set(k,now);for(const [k] of voiceSessions)if(k.startsWith(g.id+":"))voiceSessions.set(k,now);}
async function view(g,m){const c=await getGuildConfig(g.id);if(!isStaff(m,c))return null;const d=(totals.get(g.id)||new Map()).get(m.id)||{},now=Date.now(),k=g.id+":"+m.id;return {c,a:(d.activeTime||0)+(sessions.has(k)?now-sessions.get(k):0),v:(d.voiceTime||0)+(voiceSessions.has(k)?now-voiceSessions.get(k):0),msg:d.messages||0,cmd:d.commands||0};}
const data=new SlashCommandBuilder().setName("activetime").setDescription("View staff activity time.").addSubcommand(s=>s.setName("view").setDescription("View a staff member's activity.").addUserOption(o=>o.setName("user").setDescription("Staff member"))).addSubcommand(s=>s.setName("logs").setDescription("Send the daily staff report.")).addSubcommand(s=>s.setName("reset").setDescription("Reset today's activity."));
module.exports={data,async execute(i){const c=await getGuildConfig(i.guildId),s=i.options.getSubcommand();if(s==="view"){const m=await i.guild.members.fetch(i.options.getUser("user")?.id||i.user.id).catch(()=>null),x=await view(i.guild,m||i.member);if(!x)return i.reply({content:"That user is not a configured staff member.",ephemeral:true});return i.reply(card(c,EMOJIS.CLOCK+" Activity Tracker","<@"+m.id+">\n\n🟢 Online: **"+format(x.a)+"**\n🎙️ Voice: **"+format(x.v)+"**\n💬 Messages: **"+x.msg+"**\n⚙️ Commands: **"+x.cmd+"**\n\nStatus: **"+(m.presence?.status||"offline")+"**","Active Time",COLORS.SKY_BLUE));}if(!i.memberPermissions?.has(PermissionFlagsBits.ManageGuild))return i.reply({content:"You need Manage Server permission.",ephemeral:true});if(s==="logs"){const ok=await report(i.guild);return i.reply(card(c,ok?EMOJIS.SUCCESS+" Activity Report":EMOJIS.ERROR+" Activity Report",ok?"The report was sent to the configured log channel.":"Configure an Active Time log channel first.","Active Time",ok?COLORS.GREEN:COLORS.RED));}await reset(i.guild);return i.reply(card(c,EMOJIS.SUCCESS+" Activity Reset","Today's activity was saved and reset. Tracking continues now.","Active Time",COLORS.GREEN));},
register(client){client.once("ready",async()=>{for(const g of client.guilds.cache.values())await load(g);setInterval(async()=>{for(const g of client.guilds.cache.values())await snapshot(g.id).catch(e=>console.error("[ActiveTime]",e));},15*60*1000);});client.on("guildCreate",g=>load(g).catch(console.error));client.on("presenceUpdate",(o,n)=>{const m=n.member;if(!m||m.user.bot)return;getGuildConfig(m.guild.id).then(c=>{if(!isStaff(m,c))return;const k=m.guild.id+":"+m.id,on=n.status&&n.status!=="offline";if(on&&!sessions.has(k))sessions.set(k,Date.now());if(!on&&sessions.has(k)){add(totals.get(m.guild.id),m.id,"activeTime",Date.now()-sessions.get(k));sessions.delete(k);save(m.guild.id).catch(console.error);}}).catch(console.error);});client.on("voiceStateUpdate",(o,n)=>{const m=n.member||o.member;if(!m||m.user.bot)return;getGuildConfig(m.guild.id).then(c=>{if(!isStaff(m,c))return;const k=m.guild.id+":"+m.id;if(!o.channelId&&n.channelId&&!voiceSessions.has(k))voiceSessions.set(k,Date.now());if(o.channelId&&!n.channelId&&voiceSessions.has(k)){add(totals.get(m.guild.id),m.id,"voiceTime",Date.now()-voiceSessions.get(k));voiceSessions.delete(k);save(m.guild.id).catch(console.error);}}).catch(console.error);});client.on("messageCreate",async m=>{if(m.author.bot||!m.guild)return;const c=await getGuildConfig(m.guild.id).catch(()=>null);if(!c||!isStaff(m.member,c))return;const map=totals.get(m.guild.id)||new Map();add(map,m.author.id,"messages",1);const parts=m.content.trim().split(/\s+/),cmd=parts[0]?.toLowerCase();if(cmd===c.prefix+"activetime"){const t=m.mentions.members.first()||m.member,x=await view(m.guild,t);if(!x)return m.reply(card(c,EMOJIS.ERROR+" Active Time","That user is not a configured staff member.","Active Time",COLORS.RED));return m.reply(card(c,EMOJIS.CLOCK+" Activity Tracker","<@"+t.id+">\n\n🟢 Online: **"+format(x.a)+"**\n🎙️ Voice: **"+format(x.v)+"**\n💬 Messages: **"+x.msg+"**\n⚙️ Commands: **"+x.cmd+"**","Active Time",COLORS.SKY_BLUE));}if(cmd===c.prefix+"atlogs"){if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild))return;m.delete().catch(()=>{});return report(m.guild);}if(cmd===c.prefix+"resetactivetime"){if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild))return;m.delete().catch(()=>{});await reset(m.guild);return m.channel.send(card(c,EMOJIS.SUCCESS+" Activity Reset","Today's activity was saved and reset.","Active Time",COLORS.GREEN));}if(cmd===c.prefix+"removeuser"){if(!m.member.permissions.has(PermissionFlagsBits.ManageGuild))return;const u=m.mentions.users.first()||await m.guild.client.users.fetch(parts[1]).catch(()=>null);if(!u)return;m.delete().catch(()=>{});await ref(m.guild.id,u.id).delete();map.delete(u.id);return m.channel.send(card(c,EMOJIS.SUCCESS+" Activity Record Removed","Removed activity record for <@"+u.id+">.","Active Time",COLORS.GREEN));}});}};
process.on("SIGINT",async()=>{for(const g of totals.keys())await save(g).catch(()=>{});process.exit(0);});process.on("SIGTERM",async()=>{for(const g of totals.keys())await save(g).catch(()=>{});process.exit(0);});