const { SlashCommandBuilder } = require("discord.js");
const { db } = require("../firebase");
const { COLORS, EMOJIS, card } = require("../lib/ui");
const { getGuildConfig } = require("../lib/guildConfig");
const ref=(g,u)=>db.collection("guilds").doc(g).collection("afk").doc(u);
const data=new SlashCommandBuilder().setName("afk").setDescription("Set or remove your AFK status.")
.addSubcommand(s=>s.setName("set").setDescription("Set an AFK message.").addStringOption(o=>o.setName("reason").setDescription("AFK message").setMaxLength(200)))
.addSubcommand(s=>s.setName("remove").setDescription("Remove your AFK status."));
async function execute(i,c){const r=ref(i.guildId,i.user.id),sub=i.options.getSubcommand();if(sub==="remove"){if(!(await r.get()).exists)return i.reply(card(c,EMOJIS.SUCCESS+" AFK Removed","You do not currently have an AFK status.","AFK"));await r.delete();return i.reply(card(c,EMOJIS.SUCCESS+" AFK Removed","Your AFK status has been removed.","AFK",COLORS.GREEN));}const reason=i.options.getString("reason")?.trim()||"AFK";await r.set({reason,timestamp:new Date().toISOString()});return i.reply(card(c,EMOJIS.CLOCK+" AFK Enabled","You are now marked as AFK.\n\n**Message**\n"+reason,"AFK")); }
module.exports={data,execute,register(client){client.on("messageCreate",async m=>{if(m.author.bot||!m.guild)return;try{const c=await getGuildConfig(m.guild.id),r=ref(m.guild.id,m.author.id),snap=await r.get(),isCmd=m.content.startsWith(c.prefix+"afk");if(snap.exists&&!isCmd){await r.delete();await m.reply(card(c,EMOJIS.SPARKLES+" Welcome Back","Your AFK status has been removed because you are active again.","AFK",COLORS.GREEN)).catch(()=>{});}if(isCmd){const a=m.content.slice(c.prefix.length).trim().split(/ +/);a.shift();if(a[0]==="remove"){await r.delete();return m.reply(card(c,EMOJIS.SUCCESS+" AFK Removed","Your AFK status has been removed.","AFK",COLORS.GREEN));}const reason=a.join(" ").trim()||"AFK";await r.set({reason,timestamp:new Date().toISOString()});return m.reply(card(c,EMOJIS.CLOCK+" AFK Enabled","You are now marked as AFK.\n\n**Message**\n"+reason,"AFK"));}for(const u of m.mentions.users.values()){if(u.bot)continue;const s=await ref(m.guild.id,u.id).get();if(!s.exists)continue;const d=s.data();await m.reply(card(c,EMOJIS.CLOCK+" AFK Status","<@"+u.id+"> is currently AFK.\n\n**Message**\n"+(d.reason||"AFK")+"\n\n**Since**\n<t:"+Math.floor(new Date(d.timestamp).getTime()/1000)+":R>","AFK"));break;}}catch(e){console.error("AFK system error:",e);}});}};