const {PermissionsBitField,MessageFlags,ContainerBuilder,TextDisplayBuilder,SectionBuilder,ThumbnailBuilder,MediaGalleryBuilder,MediaGalleryItemBuilder}=require("discord.js");
const axios=require("axios");
const {db}=require("../firebase");
const {getGuildConfig}=require("../lib/guildConfig");
const {card,COLORS,EMOJIS}=require("../lib/ui");
const noPrefix=g=>db.collection("guilds").doc(g).collection("noPrefix");
const colors={PURPLE:0x9B59B6,BLURPLE:0x5865F2,YELLOW:0xFEE75C,WHITE:0xFFFFFF};
function reply(c,title,body,color=COLORS.SKY_BLUE,avatar=null){const content=`## ${title}\n\n${body}\n\n-# ${c.branding.name} • Misc`;const container=new ContainerBuilder().setAccentColor(color);const text=new TextDisplayBuilder().setContent(content);if(avatar)container.addSectionComponents(new SectionBuilder().addTextDisplayComponents(text).setThumbnailAccessory(new ThumbnailBuilder().setURL(avatar).setDescription("User avatar")));else container.addTextDisplayComponents(text);return {components:[container],flags:MessageFlags.IsComponentsV2,allowedMentions:{parse:[]}};}
function targetArg(message,arg){if(!arg)return message.author;const id=arg.replace(/^<@!?|>$/g,"");return message.client.users.fetch(id).catch(()=>null);}
module.exports={register(client){
 const sticky=new Map();
 client.on("messageCreate",async message=>{
  if(message.author.bot||!message.guild)return;
  const raw=message.content.trim();if(!raw)return;
  const parts=raw.split(/\s+/),first=parts.shift(),lower=first.toLowerCase();
  const cfg=await getGuildConfig(message.guild.id);
  const pref=cfg.prefix;
  const allowed=(await noPrefix(message.guild.id).doc(message.author.id).get()).exists;
  const command=lower.startsWith(pref)?lower.slice(pref.length):allowed?lower:null;
  if(!command)return;
  const args=parts;
  const avatar=message.author.displayAvatarURL({extension:"png",size:128});
  try{
   if(command==="av"||command==="avatar"){const u=await targetArg(message,args[0]);if(!u)return message.reply(reply(cfg,EMOJIS.ERROR+" Avatar","Could not find that user.",COLORS.RED,avatar));const url=u.displayAvatarURL({extension:"png",size:4096});return message.reply(reply(cfg,u.tag+"'s Avatar","**PNG:** [Open Avatar](${url})\n**User ID:** \`${u.id}\`",colors.BLURPLE,u.displayAvatarURL({extension:"png",size:128}))); }
   if(command==="ui"||command==="userinfo"){let u=await targetArg(message,args[0]);if(!u)return message.reply(reply(cfg,EMOJIS.ERROR+" User Info","Could not find that user.",COLORS.RED,avatar));const member=await message.guild.members.fetch(u.id).catch(()=>null);const roles=member?member.roles.cache.filter(r=>r.id!==message.guild.id).sort((a,b)=>b.position-a.position).map(r=>"<@&"+r.id+">").join(", "):"None";return message.reply(reply(cfg,EMOJIS.STATS+" "+u.tag,"**ID:** \`"+u.id+"\`\n**Bot:** "+(u.bot?"Yes":"No")+"\n**Account Created:** <t:"+Math.floor(u.createdTimestamp/1000)+":F>\n**Server Joined:** "+(member?.joinedTimestamp?"<t:"+Math.floor(member.joinedTimestamp/1000)+":F>":"Unknown")+"\n**Highest Role:** "+(member?.roles.highest||"None")+"\n**Roles:** "+(roles||"None"),colors.BLURPLE,u.displayAvatarURL({extension:"png",size:128}))); }
   if(command==="si"||command==="serverinfo"){const g=message.guild;return message.reply(reply(cfg,g.name+" — Server Information","**Server ID:** \`"+g.id+"\`\n**Owner:** <@"+g.ownerId+">\n**Members:** **"+g.memberCount+"**\n**Channels:** "+g.channels.cache.size+"\n**Roles:** "+g.roles.cache.size+"\n**Emojis:** "+g.emojis.cache.size+"\n**Stickers:** "+g.stickers.cache.size+"\n**Created:** <t:"+Math.floor(g.createdTimestamp/1000)+":F>",colors.PURPLE,g.iconURL({extension:"png",size:128}))); }
   if(command==="botinfo"){const users=client.guilds.cache.reduce((n,g)=>n+g.memberCount,0),s=Math.floor(client.uptime/1000);return message.reply(reply(cfg,EMOJIS.STATS+" Bot Information","**Name:** "+client.user.username+"\n**Servers:** "+client.guilds.cache.size+"\n**Users:** "+users+"\n**Ping:** "+client.ws.ping+"ms\n**Uptime:** "+Math.floor(s/86400)+"d "+Math.floor(s%86400/3600)+"h "+Math.floor(s%3600/60)+"m\n**Node:** "+process.version,colors.BLURPLE,client.user.displayAvatarURL({extension:"png",size:128}))); }
   if(command==="hide"||command==="unhide"){if(!message.member.permissions.has(PermissionsBitField.Flags.ManageChannels))return message.reply(reply(cfg,EMOJIS.ERROR+" "+command,"You need Manage Channels permission.",COLORS.RED,avatar));await message.channel.permissionOverwrites.edit(message.guild.roles.everyone,{ViewChannel:command==="hide"?false:null});return message.reply(reply(cfg,EMOJIS.SUCCESS+" Channel Updated",command==="hide"?"This channel is now hidden from @everyone.":"This channel is now visible to @everyone.",COLORS.GREEN,avatar));}
   if(command==="say"){if(!message.member.permissions.has(PermissionsBitField.Flags.ManageMessages))return message.reply(reply(cfg,EMOJIS.ERROR+" Say","You need Manage Messages permission.",COLORS.RED,avatar));const text=args.join(" ");if(!text)return message.reply(reply(cfg,EMOJIS.WARNING+" Say","Provide a message.",colors.YELLOW,avatar));await message.delete().catch(()=>{});return message.channel.send(reply(cfg,"Message",text,colors.BLURPLE));}
   if(command==="dm"){if(!message.member.permissions.has(PermissionsBitField.Flags.Administrator))return message.reply(reply(cfg,EMOJIS.ERROR+" Direct Message","You need Administrator permission.",COLORS.RED,avatar));const u=await targetArg(message,args[0]),text=args.slice(1).join(" ");if(!u||!text)return message.reply(reply(cfg,EMOJIS.WARNING+" Direct Message","Usage: "+pref+"dm @user message",colors.YELLOW,avatar));try{await u.send(reply(cfg,"Direct Message",text,colors.BLURPLE,u.displayAvatarURL({extension:"png",size:128})));return message.reply(reply(cfg,EMOJIS.SUCCESS+" DM Sent","Successfully sent a DM to **"+u.tag+"**.",COLORS.GREEN,avatar));}catch{return message.reply(reply(cfg,EMOJIS.ERROR+" DM Failed","Could not send a DM to that user.",COLORS.RED,avatar));}}
   if(command==="calculate"){const expr=args.join("");if(!expr||!/^[0-9+*/().\s-]+$/.test(expr)||/[*/+-]{3,}/.test(expr))return message.reply(reply(cfg,EMOJIS.WARNING+" Calculator","Provide a valid expression using numbers and + - * / ( ).",colors.YELLOW,avatar));try{const result=Function("\"use strict\";return ("+expr+")")();if(!Number.isFinite(result))throw 0;return message.reply(reply(cfg,EMOJIS.STATS+" Calculator","**Expression:** \`"+expr+"\`\n**Result:** \`"+result+"\`",COLORS.GREEN,avatar));}catch{return message.reply(reply(cfg,EMOJIS.ERROR+" Calculator","Could not calculate that expression.",COLORS.RED,avatar));}}
   if(command==="wiki"){const q=args.join(" ");if(!q)return message.reply(reply(cfg,EMOJIS.WARNING+" Wikipedia","Provide a search term.",colors.YELLOW,avatar));const r=await axios.get("https://en.wikipedia.org/w/api.php",{params:{action:"query",list:"search",srsearch:q,format:"json"},headers:{"User-Agent":"CommunityBot/1.0"}});const first=r.data?.query?.search?.[0];if(!first)return message.reply(reply(cfg,EMOJIS.ERROR+" Wikipedia","No matching article found.",COLORS.RED,avatar));const s=await axios.get("https://en.wikipedia.org/api/rest_v1/page/summary/"+encodeURIComponent(first.title),{headers:{"User-Agent":"CommunityBot/1.0"}});const d=s.data;return message.reply(reply(cfg,"Wikipedia: "+(d.title||first.title),(d.extract||"No summary available.")+"\n\n[Open article]("+ (d.content_urls?.desktop?.page||"https://en.wikipedia.org/wiki/"+encodeURIComponent(first.title))+")",colors.WHITE,d.thumbnail?.source||null));}
   if(command==="sticky"){if(!message.member.permissions.has(PermissionsBitField.Flags.ManageMessages))return message.reply(reply(cfg,EMOJIS.ERROR+" Sticky","You need Manage Messages permission.",COLORS.RED,avatar));const text=args.join(" ");if(!text)return message.reply(reply(cfg,EMOJIS.WARNING+" Sticky","Usage: "+pref+"sticky message | "+pref+"sticky off",colors.YELLOW,avatar));if(text.toLowerCase()==="off"){sticky.delete(message.channel.id);return message.reply(reply(cfg,EMOJIS.SUCCESS+" Sticky Removed","Sticky message removed.",COLORS.GREEN,avatar));}sticky.set(message.channel.id,{text,last:null,busy:false});await message.delete().catch(()=>{});const m=await message.channel.send(reply(cfg,EMOJIS.MESSAGE+" Sticky Message",text,colors.BLURPLE));sticky.get(message.channel.id).last=m.id;return;}
   if(command==="ip"){return message.reply(reply(cfg,EMOJIS.HOME+" Server IP","The IP command is not configured for this server. Use the bot's server-specific configuration to add an IP system later.",colors.SKY_BLUE,avatar));}
   const st=sticky.get(message.channel.id);if(st&&!st.busy&&command!=="sticky"){st.busy=true;try{if(st.last){const old=await message.channel.messages.fetch(st.last).catch(()=>null);if(old)await old.delete().catch(()=>{});}const m=await message.channel.send(reply(cfg,EMOJIS.MESSAGE+" Sticky Message",st.text,colors.BLURPLE));st.last=m.id;}finally{st.busy=false;}}
  }catch(e){console.error("[Misc] error:",e);}
 });
}};